In [1]:
import numpy as np

In [29]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1

In [30]:
arr1

array([3.5, 5. , 6. , 2. ])

In [5]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [6]:
data2

(4, 5, 3.2, 7)

In [7]:
arr2

array([4. , 5. , 3.2, 7. ])

In [8]:
arr1.ndim # arr1 ning o'lchami

1

In [9]:
arr2.ndim

1

In [11]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichida list -- nested list
arr3 = np.array(data3)

In [12]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr3.ndim

2

In [16]:
data4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] 
arr4 = np.array(data4) # 3 o'lchamli array

In [17]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# shape metodi

In [20]:
arr3.shape # qator va ustunlar soni

(2, 4)

In [21]:
arr4.shape

(2, 2, 2)

In [22]:
arr3.size # elementlar soni

8

In [23]:
arr4.size

8

In [25]:
arr5 = np.zeros((2, 4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr6 = np.ones((2, 4))
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
arr7 = np.arange(4, 30, 3) # 4 dan 30 gacha 3 qadam bilan
arr7

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [31]:
arr8 = np.arange(20)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])