In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [4]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [8]:
arr = np.array([1, 2, 3, 4]) # int64 ma'lumot turini avtomatik belgilaydi
arr

array([1, 2, 3, 4])

In [9]:
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [11]:
float_arr

array([1., 2., 3., 4.])

In [13]:
data = np.array([3.4, 5.7, 1.8, 4]) # float64 dtype ni avtomatik belgilaydi
data.dtype

dtype('float64')

In [15]:
int_data = data.astype(np.int64)
int_data

array([3, 5, 1, 4])

In [16]:
int_data.dtype

dtype('int64')