In [4]:
import numpy as np

In [5]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
arr[0]

10

In [7]:
arr[-2]

80

In [8]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
arr[3:5]

array([40, 50])

# Kesib olingan arrayga o'zgartirish kiritilsa asosiy manba array ham o'zgaradi

In [10]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [12]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

# copy usuli haqida

In [13]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [15]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# 2 o'lchamli massiv

In [16]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[1, 2]

6

In [25]:
sl_arr2d = arr2d[2, 1:]
sl_arr2d

array([8, 9])

In [32]:
sl_arr2d_2 = arr2d[:2, 2:]
sl_arr2d_2

array([[3],
       [6]])

In [31]:
sl_arr2d_2.shape

(2,)

# 3D array

In [33]:
# 3D array
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
arr3d[0][1,2]

5