In [1]:
import numpy as np

In [2]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
# data
data = np.random.randn(7, 4)
data

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.93651911, -1.26692987, -1.56062691, -0.6733265 ],
       [ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007],
       [ 1.97874152,  0.79322479, -0.59049792,  1.73702037],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [4]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [5]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007]])

In [6]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [7]:
data[names=='Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[ 1.51212277, -2.03087021],
       [ 0.54376738, -0.43812007]])

In [8]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.93651911, -1.26692987, -1.56062691, -0.6733265 ],
       [ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [ 1.97874152,  0.79322479, -0.59049792,  1.73702037],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [9]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan

array([[-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.93651911, -1.26692987, -1.56062691, -0.6733265 ],
       [ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [ 1.97874152,  0.79322479, -0.59049792,  1.73702037],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [10]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 0.09604439  0.83321303  1.51212277 -2.03087021]
 [-1.00929903 -0.30654716 -0.80309278  1.17522858]
 [-0.93651911 -1.26692987 -1.56062691 -0.6733265 ]
 [ 0.74873211 -1.31841861 -1.30713015 -0.24218478]
 [-0.75377677 -0.51559069  0.54376738 -0.43812007]
 [ 1.97874152  0.79322479 -0.59049792  1.73702037]
 [-0.83828825  0.68336996  2.44175602  2.04284262]]


In [11]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [12]:
data[mask] # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007]])

In [13]:
data

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.93651911, -1.26692987, -1.56062691, -0.6733265 ],
       [ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007],
       [ 1.97874152,  0.79322479, -0.59049792,  1.73702037],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [14]:
data[mask]

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007]])

In [15]:
data

array([[ 0.09604439,  0.83321303,  1.51212277, -2.03087021],
       [-1.00929903, -0.30654716, -0.80309278,  1.17522858],
       [-0.93651911, -1.26692987, -1.56062691, -0.6733265 ],
       [ 0.74873211, -1.31841861, -1.30713015, -0.24218478],
       [-0.75377677, -0.51559069,  0.54376738, -0.43812007],
       [ 1.97874152,  0.79322479, -0.59049792,  1.73702037],
       [-0.83828825,  0.68336996,  2.44175602,  2.04284262]])

In [18]:
data[data<0] = 0 # manfiy qiymatlarni 0 ga tenglash

In [17]:
data

array([[0.09604439, 0.83321303, 1.51212277, 0.        ],
       [0.        , 0.        , 0.        , 1.17522858],
       [0.        , 0.        , 0.        , 0.        ],
       [0.74873211, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.54376738, 0.        ],
       [1.97874152, 0.79322479, 0.        , 1.73702037],
       [0.        , 0.68336996, 2.44175602, 2.04284262]])