# transpose - massiv holatini o'zgartirish

In [1]:
import numpy as np

**reshape** metodi

In [2]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [4]:
A.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [5]:
np.dot(A, A.T) # A*A^T, ya'ni, massivlarni ko'paytiryapmiz

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])