In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr1 = np.random.randn(6)
arr1

array([-1.56080553, -0.79118014, -1.53406322,  0.70595965,  1.66761341,
       -0.75658755])

In [7]:
qoldiq, butun = np.modf(arr1)

In [8]:
print(qoldiq)
print(butun)

[-0.56080553 -0.79118014 -0.53406322  0.70595965  0.66761341 -0.75658755]
[-1. -0. -1.  0.  1. -0.]


In [9]:
np.sign(arr1)

array([-1., -1., -1.,  1.,  1., -1.])

In [10]:
arr1

array([-1.56080553, -0.79118014, -1.53406322,  0.70595965,  1.66761341,
       -0.75658755])

In [11]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [14]:
arr1[0] = np.NaN
arr1

array([        nan, -0.79118014, -1.53406322,  0.70595965,  1.66761341,
       -0.75658755])

In [16]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

# Binary funksiyalar

In [17]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [18]:
arr2

array([ 0.66775968, -0.81895514,  0.88009604,  0.25370244, -0.69839334,
       -0.43757409])

In [19]:
arr3

array([-0.71955205,  0.24127199, -0.99960427,  0.02962422, -1.92713018,
        0.06747519])

In [20]:
np.add(arr2, arr3) # arraylarni mos ravishda qo'shish

array([-0.05179238, -0.57768315, -0.11950823,  0.28332666, -2.62552352,
       -0.3700989 ])

In [21]:
arr2 + arr3

array([-0.05179238, -0.57768315, -0.11950823,  0.28332666, -2.62552352,
       -0.3700989 ])

In [22]:
np.multiply(arr2, arr3)

array([-0.48048784, -0.19759094, -0.87974776,  0.00751574,  1.34589488,
       -0.0295254 ])

In [23]:
np.maximum(arr2, arr3)

array([ 0.66775968,  0.24127199,  0.88009604,  0.25370244, -0.69839334,
        0.06747519])