In [6]:
import numpy as np

In [7]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [8]:
# Shart
cond = np.array([True, False, True, True, False])

In [9]:
# where
result = np.where(cond, xarr, yarr) # cond ==True : xarr, cond==False : yrr
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [11]:
arr = np.random.randn(4,4)
arr

array([[ 1.3680338 ,  0.97326255, -0.09486709, -1.24362668],
       [-1.63601153,  1.11865271,  2.06528447, -0.07600031],
       [ 0.19055563,  0.53757589,  0.49392564, -2.77581781],
       [ 0.40396376, -0.76690934, -0.70662591, -0.03283894]])

In [13]:
# where
results = np.where(arr<0, -2, 2) # если()
results

array([[ 2,  2, -2, -2],
       [-2,  2,  2, -2],
       [ 2,  2,  2, -2],
       [ 2, -2, -2, -2]])