In [1]:
import numpy as np

In [2]:
# data
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
# Ko'paytirish
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [6]:
# Bo'lish
arr2 / arr1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [7]:
# Qo'shish
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [8]:
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [9]:
arr1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [10]:
arr2 ** 0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])