In [1]:
import numpy as np

In [22]:
# data
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# sum metodi

In [23]:
arr.sum() # arrayning barcha elem yigindisi

66

In [24]:
np.sum(arr)

66

In [25]:
arr.sum(axis=1) # qator yig'indisi

array([ 6, 22, 38])

In [26]:
arr.sum(axis=0) # ustundagi elementlar yig'indisi

array([12, 15, 18, 21])

# mean metodi

In [27]:
# sodda ma'lumot
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [28]:
mean = np.sum(data) / len(data) # o'rta arif. qiymat
mean

2.0

In [29]:
# numpy da mean
np.mean(data)

2.0

In [30]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.mean(arr)

5.5

In [32]:
np.mean(arr, axis=1) # qator bo'yicha o'rtacha qiymat

array([1.5, 5.5, 9.5])

In [33]:
np.mean(arr, axis=0) # ustun bo'yicha o'rtacha qiymat

array([4., 5., 6., 7.])

In [34]:
arr.mean(axis=0) # ustun bo'yicha o'rtacha qiymat

array([4., 5., 6., 7.])

# cumsum metodi

In [35]:
data

array([0, 1, 2, 3, 4])

In [36]:
data.cumsum()

array([ 0,  1,  3,  6, 10])