In [1]:
import numpy as np

In [2]:
arr = np.random.rand(4)
arr

array([0.92709056, 0.3990673 , 0.15278594, 0.75803722])

# sort funksiyasi

In [3]:
sorted_arr = np.sort(arr) # tartiblangan yangi array
sorted_arr

array([0.15278594, 0.3990673 , 0.75803722, 0.92709056])

In [4]:
# 2-usul
arr.sort() # asl arrayning tartiblangani
arr

array([0.15278594, 0.3990673 , 0.75803722, 0.92709056])

In [5]:
# teskari tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([0.92709056, 0.75803722, 0.3990673 , 0.15278594])

In [6]:
# 2D array
arr2d = np.random.randn(2, 4)
arr2d

array([[ 1.0759912 , -0.23962773, -0.09748316, -0.91205273],
       [ 1.5680901 ,  0.34457785,  0.50429937,  0.74270092]])

In [7]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0)
row_srt

array([[ 1.0759912 , -0.23962773, -0.09748316, -0.91205273],
       [ 1.5680901 ,  0.34457785,  0.50429937,  0.74270092]])

In [8]:
col_srt = np.sort(arr2d, axis=1)
col_srt

array([[-0.91205273, -0.23962773, -0.09748316,  1.0759912 ],
       [ 0.34457785,  0.50429937,  0.74270092,  1.5680901 ]])