In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# faylni saqlash
np.save('data', arr) # 2 lik sanoq sistemasida saqlayapmiz

In [6]:
# faylni chaqirib, arr2  ga o'zlashtiramiz
arr2 = np.load('data.npy')

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 = np.arange(20)

In [11]:
np.savez('arrays', a=arr, b=arr1)

In [12]:
arrays = np.load('arrays.npz')

In [13]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)