In [8]:
import numpy as np

In [9]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
y = np.array([[5., 5., 5.], [4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [11]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [12]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [14]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [15]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [19]:
x.dot(y) # x*y

array([[ 28.,  64.],
       [ 67., 181.]])

In [20]:
np.dot(x, y) # x*y

array([[ 28.,  64.],
       [ 67., 181.]])

In [21]:
y.dot(x) # y*x

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [22]:
np.dot(y, x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [23]:
# Linear Algebra
from numpy.linalg import inv

https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060